#!/bin/bash

echo
while getopts :ab:cd opt
do
  case "$opt" in
    a) echo "a option" ;;
    b) echo "b option with $OPTARG" ;;
    c) echo "c option" ;;
    d) echo "d option" ;;
  esac
done
#
shift $[ $OPTIND - 1 ]
#
echo
count=1
for param in "$@"
do
  echo "parameter $count: $param"
  count=$[ $count + 1 ]
done
